from colorama import Back, Style
import random

# generates number
random_number = random.randint(1, 20)

while True:
    # guess a random number generated by Python between 1 and 20
    inputted_number = int(input("Guess the number (1-20):\n"))
    # if right number
    if inputted_number == random_number:
        print(Back.GREEN + "CONGRATULATIONS!!")
        break
        # if guess is higher
    elif inputted_number > random_number:
        print(Back.RED + "Too high")
        print(Style.RESET_ALL)
        # if guess is lower
    elif inputted_number < random_number:
        print(Back.BLUE + "Too low")
        print(Style.RESET_ALL)
